### PR TITLE
Test

### PR DESCRIPTION
**Pull request by jdmanuel**
this_and_that

_this_

### CODE REVIEW

**Comment by jdmanuel** [comment]
_does_this_work_

**Comment by mattr-** [comment]
Are you trying to figure out how to not have underscore emphasis on GitHub? If so, then prefix your first underscore with a slash, like so: `\_`

 \_that_will_keep_the_emphasis_away_

**Comment by jdmanuel** [comment]
Hey @mattr- .  Thanks.  Yeah, problem is that we're currently using redcarpet 2.1.1.  And with this, email addresses like this: a\_b\_@zendesk.com aren't rendered correctly.  Bumping the gem to 3.2.x, this is fixed, but then things like \_this\_is\_me\_ aren't emphasized properly.  Can't seem to have our cake and eat it too...  Noticed that both work properly with github-flavored-markdown, though.  Maybe with redcarpet too, and we're just doing something wrong?

**Comment by jdmanuel** [comment]
sorry, thought i made this PR against my forked version :/  damn

**Comment by mattr-** [comment]
GitHub doesn't use Redcarpet for markdown rendering anymore, it's actually driven by [jch/html-pipeline](https://github.com/jch/html-pipeline) and friends instead. Knowing what options you're using with Redcarpet might help. There's probably something that could be put in play here with the `:no_intra_emphasis` option for the renderer.

**Comment by jdmanuel** [comment]
Thanks again, Matt.  Right now, we've got:
```
      :autolink            => true,
      :space_after_headers => true,
      :no_intra_emphasis   => true,
      :fenced_code_blocks  => true
```

**Pull request closed without merging**
