### PR TITLE
Setup GitHub Actions

### PR DESCRIPTION
**Pull request by casperisfine**
As discussed in https://github.com/vmg/redcarpet/pull/721

cc @robin850

### CODE REVIEW

**Comment by casperisfine** [comment]
Test build: https://github.com/casperisfine/redcarpet/runs/5812829225, 2.1 and older fail because we'd need to install an older rake version.

I chose to remove 2.1 and older given how old they are, but I can also try to fix them if you feel strongly about it.

**Comment by mishina2228** [comment]
Duplicate with #725?

**Comment by mishina2228** [comment]
Duplicate with #725?

**Comment by robin850** [comment]
Hello,

I am so sorry for being so long to treat this but the patch of #725 has been applied; you've been credited as a co-author.

Thank you very much, Jean! ❤️

**Pull request closed without merging**
