### PR TITLE
Include cell header information in table_cell callback.

### PR DESCRIPTION
**Pull request by mlambley**
Copy flag bitmask logic from html.c to rc_render.c. 
Pass whether or not the cell is a header (th) to the table_cell callback. 
Update readme and render_strip to match.

### CODE REVIEW

**Comment by mlambley** [comment]
Example code for override:

    def table_cell(content, alignment, header)
        if alignment
            class = " class='" + alignment + "'"
        else
            class = ""
        end
        
        if header
            "<th" + class + ">" + content + "</th>"
        else
            "<td" + class + ">" + content + "</td>"
        end
    end

**Comment by robin850** [comment]
Hi @mlambley,

The problem with your patch is that it would introduce a breaking change ; a render object wouldn't work with the current version of Redcarpet and the next one. Let me think about this a bit more, maybe we could look at the method's arity to know how many arguments should be passed.

Thank you very much for the pull request, getting back to you soon ! :-)

**Comment by mlambley** [comment]
@robin850 How often do you release breaking changes? I'm happy to spruce up this PR if necessary if it means being merged sometime soon.

**Comment by robin850** [comment]
Hello @mlambley,

I lied when I said "getting back to you soon" but your patch has been polished a bit to be backward compatible. You can find the final patch in https://github.com/vmg/redcarpet/commit/27dfb2a738a23aadd286ac9e7ecd61c4545d29de ; you've been properly credited. This should be available once Redcarpet 3.6.0 is released.

Thank you very much and sorry for the lasting status quo. ❤️

**Pull request closed without merging**
