### PR TITLE
CI on GitHub Actions

### PR DESCRIPTION
**Pull request by amatsuda**
Here's an attempt to run the CI on GitHub Actions.

Ruby versions in the matrix covers all tested versions on the previous Travis one, plus, 3.0 and 3.1 that were not tested on Travis.

### CODE REVIEW

**Comment by amatsuda** [comment]
Maybe Actions has to be enabled at the repo setting? https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository

**Comment by petergoldstein** [comment]
You may want to:

1) Add Ruby 3.2 to the matrix
2) Consider using the `bundler-cache` option on `ruby/setup-ruby` over running `bundle` manually since it better handles using compatible bundler versions.

**Comment by amatsuda** [comment]
@petergoldstein Did so! (I don't think that ruby 1.x won't run on GHA though)

**Comment by petergoldstein** [comment]
@amatsuda Very possibly not.  Honestly at this point I'd move the minimum cutoff to 2.2 or possibly even a more recent version.

**Comment by robin850** [comment]
Hello,

I am so sorry for being so long to treat this but your patch has been applied on `master` with some tweaks to run on latest GitHub Actions.

Thank you very much, this was needed! ❤️

**Pull request closed without merging**
